"""add_username_to_users

Revision ID: 302230155e2e
Revises: ac0d371fd779
Create Date: 2025-12-07 09:12:15.563417

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
import random


# revision identifiers, used by Alembic.
revision: str = '302230155e2e'
down_revision: Union[str, Sequence[str], None] = 'ac0d371fd779'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('username', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    
    # Backfill existing users
    connection = op.get_bind()
    results = connection.execute(sa.text("SELECT id FROM \"user\""))
    for row in results:

        random_num = random.randint(1000, 9999)
        username = f"user#{random_num}"
        connection.execute(
            sa.text("UPDATE \"user\" SET username = :username WHERE id = :id"),
            {"username": username, "id": row[0]}
        )

    op.alter_column('user', 'username', nullable=False)
    op.create_index(op.f('ix_user_username'), 'user', ['username'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_username'), table_name='user')
    op.drop_column('user', 'username')
    # ### end Alembic commands ###
